[package]
name = "mvs-sys"
version = "0.1.0"
authors = ["Yawara ISHIDA <ni732h.sphl@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
build = "build.rs"

